on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: make setup

      - name: run linters
        run: make lint

      - name: run tests
        run: make test
